This notebook cleans and verifys that the parquets for Humboldt, Chico, Somona, Sac, San Fran, San Berninadino, Pomona are of the following schema:
- Name (First Last)
- School
- Department
- Title
- Major (null if they don't have)

In [3]:
humboldt_data = ""
chico_data = "../Data/chico_faculty.parquet"
somona_data = ""
sac_data = "../Data/csusac_faculty.parquet"
sfsu_data = "../Data/sfsu_faculty.parquet"
sanbern_data = ""
pomona_data = ""

In [2]:
import pandas as pd
import duckdb
import numpy as np

In [4]:
chico_df = pd.read_parquet(chico_data)
chico_df.head(5)

,name,title,department,school,year
0,Dawn M Abel,Lecturer,Nursing,"California State University, Chico",2013
1,Annie Adamian,Associate Professor,Education,"California State University, Chico",2014
2,Nora A Aguilar McKay,Lecturer,Education,"California State University, Chico",2014
3,Kelsey R Aguire,Lecturer,Nursing,"California State University, Chico",2025
4,Kirk D Aiken,Professor,Marketing,"California State University, Chico",2013

- Name needs to be cleaned (remove middle initial)

In [ ]:
from pathlib import Path

chico_df["name"] = (
    chico_df["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.replace(r"(?i),? (?:Jr\.?|Sr\.?|II|III|IV)$", "", regex=True)
)

chico_output = Path(chico_data).with_name("chico_cleaned.parquet")
chico_df.to_parquet(chico_output, index=False)
chico_df.head(5)

,name,title,department,school,year
0,Dawn Abel,Lecturer,Nursing,"California State University, Chico",2013
1,Annie Adamian,Associate Professor,Education,"California State University, Chico",2014
2,Nora Aguilar McKay,Lecturer,Education,"California State University, Chico",2014
3,Kelsey Aguire,Lecturer,Nursing,"California State University, Chico",2025
4,Kirk Aiken,Professor,Marketing,"California State University, Chico",2013

In [8]:
sac_df = pd.read_parquet(sac_data)
sac_df.head(5)

,name,title,department,school,start_date
0,"ABADI, MASOUD",Assistant Professor of Civil Engineering,Civil Engineering,"California State University, Sacramento",2018
1,"ABAH, TERESA",Assistant Professor of Gerontology,Gerontology,"California State University, Sacramento",2020
2,"ABENDROTH, KATHLEEN","Maryjane Rees Language, Speech and Hearing Cen...",CSAD,"California State University, Sacramento",2022
3,"ABULHASSAN, YOUSIF A.",Associate Professor of Public Health,Public Health,"California State University, Sacramento",2022
4,"ACEVES-AZUARA, ITZEL",Assistant Professor of Psychology,Psychology,"California State University, Sacramento",2022

Name and Title need to be cleaned:

In [ ]:
sac_df["name"] = (
    sac_df["name"]
    .str.replace(r"^\s*([^,]+),\s*(.+?)\s*$", r"\2 \1", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.title()
)
sac_df["title"] = (
    sac_df["title"]
    .str.split(r"\s+of\s+", n=1, regex=True)
    .str[0]
    .str.strip()
)
sac_output = Path(sac_data).with_name("sac_cleaned.parquet")
sac_df.to_parquet(sac_output, index=False)
sac_df.head(5)

,name,title,department,school,start_date
0,Masoud Abadi,Assistant Professor,Civil Engineering,"California State University, Sacramento",2018
1,Teresa Abah,Assistant Professor,Gerontology,"California State University, Sacramento",2020
2,Kathleen Abendroth,"Maryjane Rees Language, Speech and Hearing Cen...",CSAD,"California State University, Sacramento",2022
3,Yousif Abulhassan,Associate Professor,Public Health,"California State University, Sacramento",2022
4,Itzel Aceves-Azuara,Assistant Professor,Psychology,"California State University, Sacramento",2022

In [11]:
sfsu_df = pd.read_parquet(sfsu_data)
sfsu_df.head(5)

,name,title,department,school,start_date
0,Miguel Abad,Assistant Professor in Child and Adolescent De...,Child and Adolescent Development,San Francisco State University,2022
1,Bárbara I. Abadía-Rexach,Associate Professor in Latina/Latino Studies,Latina/Latino Studies,San Francisco State University,2020
2,Shadee Abdi,Associate Professor in Communication Studies,Communication Studies,San Francisco State University,2019
3,Rabab Abdulhadi,Associate Professor in Race and Resistance Stu...,Race and Resistance Studies,San Francisco State University,2007
4,Priyanvada Abeywickrama,Professor in English Language and Literature,English Language and Literature,San Francisco State University,2007

Name and title need to be cleaned

In [15]:
sfsu_df["name"] = (
    sfsu_df["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.replace(r"(?i),? (?:Jr\.?|Sr\.?|II|III|IV)$", "", regex=True)
)

sfsu_df["title"] = (
    sfsu_df["title"]
    .str.split(r"\s+in\s+", n=1, regex=True)
    .str[0]
    .str.strip()
)

sfsu_output = Path(sfsu_data).with_name("sfsu_cleaned.parquet")
sfsu_df.to_parquet(sfsu_output, index=False)
sfsu_df.head(5)

,name,title,department,school,start_date
0,Miguel Abad,Assistant Professor,Child and Adolescent Development,San Francisco State University,2022
1,Bárbara Abadía-Rexach,Associate Professor,Latina/Latino Studies,San Francisco State University,2020
2,Shadee Abdi,Associate Professor,Communication Studies,San Francisco State University,2019
3,Rabab Abdulhadi,Associate Professor,Race and Resistance Studies,San Francisco State University,2007
4,Priyanvada Abeywickrama,Professor,English Language and Literature,San Francisco State University,2007