This notebook cleans and verifys that the parquets for Humboldt, Chico, Somona, Sac, San Fran, San Berninadino, Pomona are of the following schema:
- Name (First Last)
- School
- Department
- Title
- Major (null if they don't have)

In [114]:
humboldt_data = "../Data/humboldt_faculty.parquet"
chico_data = "../Data/chico_faculty.parquet"
sonoma_data = "../Data/sonoma_faculty.parquet"
sac_data = "../Data/csusac_faculty.parquet"
sfsu_data = "../Data/sfsu_faculty.parquet"
sanbern_data = "../Data/csusb_faculty.parquet"
pomona_data = "../Data/cpp_faculty.parquet"
dh_data = "../Data/csudh_faculty.parquet"

In [26]:
import pandas as pd
import duckdb
import numpy as np
from pathlib import Path

In [27]:
chico_df = pd.read_parquet(chico_data)
chico_df.head(5)

,name,title,department,school,year
0,Dawn M Abel,Lecturer,Nursing,"California State University, Chico",2013
1,Annie Adamian,Associate Professor,Education,"California State University, Chico",2014
2,Nora A Aguilar McKay,Lecturer,Education,"California State University, Chico",2014
3,Kelsey R Aguire,Lecturer,Nursing,"California State University, Chico",2025
4,Kirk D Aiken,Professor,Marketing,"California State University, Chico",2013

In [31]:
chico_df['title'].unique().tolist()

['Lecturer',
 'Associate Professor',
 'Professor',
 'Assistant Professor',
 'Chair',
 'Grsf If 12',
 'Director',
 'Vice Chair',
 'Program Coordinator',
 'Instructor',
 'Assistant Director',
 'Emeritus']

- Name needs to be cleaned (remove middle initial)

In [ ]:


chico_df["name"] = (
    chico_df["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.replace(r"(?i),? (?:Jr\.?|Sr\.?|II|III|IV)$", "", regex=True)
)

chico_output = Path(chico_data).with_name("chico_cleaned.parquet")
chico_df.to_parquet(chico_output, index=False)
chico_df.head(5)

,name,title,department,school,year
0,Dawn Abel,Lecturer,Nursing,"California State University, Chico",2013
1,Annie Adamian,Associate Professor,Education,"California State University, Chico",2014
2,Nora Aguilar McKay,Lecturer,Education,"California State University, Chico",2014
3,Kelsey Aguire,Lecturer,Nursing,"California State University, Chico",2025
4,Kirk Aiken,Professor,Marketing,"California State University, Chico",2013

In [113]:
chico_df.shape

(1468, 5)

In [48]:
sac_df = pd.read_parquet(sac_data)
sac_df.head(5)

,name,title,department,school,start_date
0,"ABADI, MASOUD",Assistant Professor of Civil Engineering,Civil Engineering,"California State University, Sacramento",2018
1,"ABAH, TERESA",Assistant Professor of Gerontology,Gerontology,"California State University, Sacramento",2020
2,"ABENDROTH, KATHLEEN","Maryjane Rees Language, Speech and Hearing Cen...",CSAD,"California State University, Sacramento",2022
3,"ABULHASSAN, YOUSIF A.",Associate Professor of Public Health,Public Health,"California State University, Sacramento",2022
4,"ACEVES-AZUARA, ITZEL",Assistant Professor of Psychology,Psychology,"California State University, Sacramento",2022

In [39]:
sac_df['title'].nunique()

337

clean titles:

In [52]:
# Replace df with your dataframe name.
titles = (
    sac_df["title"]
    .astype("string")
    .str.strip()
    .str.replace(r"\bAssoiciate\b", "Associate", regex=True, case=False)
    .str.replace(r"\bProfesssor\b", "Professor", regex=True, case=False)
)

# Put more specific titles before their shorter versions.
pattern = (
    r"(?i)\b("
    r"Senior Assistant Librarian|"
    r"Assistant Professor|"
    r"Associate Professor|"
    r"Professor|"
    r"Full-Time Lecturer|"
    r"Lecturer|"
    r"Librarian"
    r")\b"
)

matched = titles.str.extract(pattern, expand=False)
sac_df["title_clean"] = matched.str.title().fillna(titles)
# Keep unmatched titles for review instead of dropping them.
sac_df["title"] = sac_df["title_clean"].fillna(sac_df["title"])
sac_df["title"] = sac_df["title"].replace(
    "AssociateProfessor of Physical Therapy",
    "Associate Professor"
)
sac_df.drop(columns=["title_clean"], inplace=True)

In [50]:
sac_df['title'].unique().tolist()

['Assistant Professor',
 'Full-Time Lecturer',
 'Associate Professor',
 'Professor',
 'Librarian',
 'Lecturer',
 'Senior Assistant Librarian',
 'MPP; Associate Dean for Collections & Discovery, University Library',
 'MPP; Dean, University Library',
 'MPP; Associate Dean for Academic Services, University Library',
 'Full-time Temporary']

Clean Name

In [53]:
sac_df["name"] = (
    sac_df["name"]
    .str.replace(r"^\s*([^,]+),\s*(.+?)\s*$", r"\2 \1", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.title()
)
sac_output = Path(sac_data).with_name("sac_cleaned.parquet")
sac_df.to_parquet(sac_output, index=False)
sac_df.head(5)

,name,title,department,school,start_date
0,Masoud Abadi,Assistant Professor,Civil Engineering,"California State University, Sacramento",2018
1,Teresa Abah,Assistant Professor,Gerontology,"California State University, Sacramento",2020
2,Kathleen Abendroth,Full-Time Lecturer,CSAD,"California State University, Sacramento",2022
3,Yousif Abulhassan,Associate Professor,Public Health,"California State University, Sacramento",2022
4,Itzel Aceves-Azuara,Assistant Professor,Psychology,"California State University, Sacramento",2022

In [112]:
sac_df.shape

(807, 5)

In [11]:
sfsu_df = pd.read_parquet(sfsu_data)
sfsu_df.head(5)

,name,title,department,school,start_date
0,Miguel Abad,Assistant Professor in Child and Adolescent De...,Child and Adolescent Development,San Francisco State University,2022
1,Bárbara I. Abadía-Rexach,Associate Professor in Latina/Latino Studies,Latina/Latino Studies,San Francisco State University,2020
2,Shadee Abdi,Associate Professor in Communication Studies,Communication Studies,San Francisco State University,2019
3,Rabab Abdulhadi,Associate Professor in Race and Resistance Stu...,Race and Resistance Studies,San Francisco State University,2007
4,Priyanvada Abeywickrama,Professor in English Language and Literature,English Language and Literature,San Francisco State University,2007

Name and title need to be cleaned

In [56]:
sfsu_df["name"] = (
    sfsu_df["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.replace(r"(?i),? (?:Jr\.?|Sr\.?|II|III|IV)$", "", regex=True)
)

sfsu_df["title"] = (
    sfsu_df["title"]
    .str.split(r"\s+in\s+", n=1, regex=True)
    .str[0]
    .str.strip()
)
sfsu_df["title"] = sfsu_df["title"].replace(
    "Estuary and Ocean Science Center Research Professor, Adjunct Professor",
    "Adjunct Professor"
)

sfsu_output = Path(sfsu_data).with_name("sfsu_cleaned.parquet")
sfsu_df.to_parquet(sfsu_output, index=False)
sfsu_df.head(5)

,name,title,department,school,start_date
0,Miguel Abad,Assistant Professor,Child and Adolescent Development,San Francisco State University,2022
1,Bárbara Abadía-Rexach,Associate Professor,Latina/Latino Studies,San Francisco State University,2020
2,Shadee Abdi,Associate Professor,Communication Studies,San Francisco State University,2019
3,Rabab Abdulhadi,Associate Professor,Race and Resistance Studies,San Francisco State University,2007
4,Priyanvada Abeywickrama,Professor,English Language and Literature,San Francisco State University,2007

In [111]:
sfsu_df.shape

(687, 5)

In [73]:
humboldt_df = pd.read_parquet(humboldt_data)
humboldt_df.head(5)

,name,school,department,title,major
0,AJ Murphy,Cal Poly Humboldt,"Forest, Fire, Range",Lecturer,<NA>
1,Aaron Donaldson,Cal Poly Humboldt,Communication,Lecturer,<NA>
2,Aaron Hohl,Cal Poly Humboldt,"Forest, Fire, Range",Lecturer,<NA>
3,Aaron Phelps,Cal Poly Humboldt,NorCal SBDC,Marketing Director,<NA>
4,Aaron Sweat,Cal Poly Humboldt,FacMgt- Plan/Des/Con,Senior Designer,<NA>

In [74]:
allowed_titles = [
    "Assistant Professor",
    "Teacher",
    "Associate Professor",
    "Professor",
    "Lecturer",
    "Lecturer AY",
    "Instructional Faculty",
    "Instructor",
    "Chair",
    "Director",
    "Grsf If 12",
    "Adjunct Professor",
    "Associate Librarian",
    "Librarian",
    "Adjunct Assistant Professor",
    "Associate Clinical Professor",
    "Senior Lecturer",
    "Full-Time Lecturer",
    "Full-time Temporary",
]

humboldt_df = humboldt_df[humboldt_df["title"].isin(allowed_titles)].copy()
humboldt_output = Path(humboldt_data).with_name("humboldt_cleaned.parquet")
humboldt_df.to_parquet(humboldt_output, index=False)
humboldt_df.head(5)

               name             school           department     title major
0         AJ Murphy  Cal Poly Humboldt  Forest, Fire, Range  Lecturer  <NA>
1   Aaron Donaldson  Cal Poly Humboldt        Communication  Lecturer  <NA>
2        Aaron Hohl  Cal Poly Humboldt  Forest, Fire, Range  Lecturer  <NA>
6     Abigail Queen  Cal Poly Humboldt              History  Lecturer  <NA>
7  Abigail Smithson  Cal Poly Humboldt           Art + Film  Lecturer  <NA>

In [110]:
humboldt_df.shape

(586, 5)

In [87]:
sonoma_df = pd.read_parquet(sonoma_data)
sonoma_df.head(5)

,name,school,department,title,major
0,Aaron Westman,Sonoma State University,Department of Music,Special Consultant - Hourly,<NA>
1,Aaron Westman,Sonoma State University,Music Studio,Lecturer AY,<NA>
2,Abbie Page,Sonoma State University,Office of Student Involvement,Fraternity and Sorority Life Advisor,<NA>
3,Adam Hill,Sonoma State University,Department of Counseling,Instructional Faculty,<NA>
4,Adam Jarman,Sonoma State University,University Development,Associate Vice President for Development,<NA>

In [89]:
sonoma_df.shape

(392, 5)

In [88]:
sonoma_allowed_titles = [
    "Lecturer AY",
    "Instructional Faculty",
    "Instructor",
    "Chair",
    "Director",
    "Grsf If 12",
    "Instr Fac,Extension Non-Credit",
    "Instr Fac,Spcl Pgms-For Credit",
    "Instr Fac 12 Mo",
    "Grnt Rltd Spc Fnd Inst Fac AY",
    # Include chairs and librarians, consistent with your broader list:
    "Dept Chair AY",
    "Dept Chair 12 Mo",
    "Librarian 12 Mo",
]
sonoma_df = sonoma_df[sonoma_df["title"].isin(sonoma_allowed_titles)].copy()
sonoma_output = Path(sonoma_data).with_name("sonoma_cleaned.parquet")
sonoma_df.to_parquet(sonoma_output, index=False)
sonoma_df.head(5)

,name,school,department,title,major
1,Aaron Westman,Sonoma State University,Music Studio,Lecturer AY,<NA>
3,Adam Hill,Sonoma State University,Department of Counseling,Instructional Faculty,<NA>
6,Adam Zagelbaum,Sonoma State University,Department of Counseling,Instructional Faculty,<NA>
7,Adele Santana,Sonoma State University,Business Administration,Instructional Faculty,<NA>
14,Aidong Hu,Sonoma State University,Business Administration,Instructional Faculty,<NA>

In [109]:
sonoma_df.shape

(392, 5)

In [97]:
pomona_df = pd.read_parquet(pomona_data)
pomona_df.head(5)

,name,school,department,title,major
0,Aaron F. Cayer,Cal Poly Pomona,Architecture,Associate Professor,<NA>
1,Aaron F. Fox,Cal Poly Pomona,Department of Plant Science,Associate Professor,<NA>
2,Aaron M DeRosa,Cal Poly Pomona,English and Modern Languages,Assistant Professor,<NA>
3,Abdelfattah Amamra,Cal Poly Pomona,Computer Science,Associate Professor,<NA>
4,Abhishek Tiwari,Cal Poly Pomona,Urban and Regional Planning,<NA>,<NA>

clean middle initial

In [ ]:
pomona_df["name"] = (
    pomona_df["name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.replace(r"(?<=\S) (?:[A-Za-z]\.? )+(?=\S)", " ", regex=True)
    .str.replace(r"(?i),? (?:Jr\.?|Sr\.?|II|III|IV)$", "", regex=True)
)

,name,school,department,title,major
0,Aaron Cayer,Cal Poly Pomona,Architecture,Associate Professor,<NA>
1,Aaron Fox,Cal Poly Pomona,Department of Plant Science,Associate Professor,<NA>
2,Aaron DeRosa,Cal Poly Pomona,English and Modern Languages,Assistant Professor,<NA>
3,Abdelfattah Amamra,Cal Poly Pomona,Computer Science,Associate Professor,<NA>
4,Abhishek Tiwari,Cal Poly Pomona,Urban and Regional Planning,<NA>,<NA>

In [92]:
pomona_df['title'].unique().tolist()

['Associate Professor',
 'Assistant Professor',
 <NA>,
 'Emeritus Professor, Advisor',
 'Adjunct Professor',
 'Professor',
 'Professor, Director of The Democracy Institute',
 'Lecturer',
 'Professor and Acting Chair',
 'Professional Practice Professor',
 'Associate Professor of Applied Linguistics/TESOL',
 'Professor Emeritus',
 'Chair and Professor',
 'Associate Professor of Anthropology',
 'Professor Emerita',
 'Professor of Biological Sciences',
 'Adjunct Faculty/Lecturer',
 'Sociology Professor',
 'Assistant Professor of Anthropology',
 'Associate Professor/Interim Chair',
 'Professor and Program Director for Sociology',
 'Assistant Professor of Environmental and Science Education',
 'Chair, Associate Professor',
 'Adjunct Professor of Engineering',
 'Program Director',
 'Basketball Coach',
 'Professor Emerita, Nutrition',
 'MPA Director',
 'Associate Professor & Production Manager',
 'Visiting Faculty',
 'Professor and Department Chair, Economics',
 'Title',
 'Professor of Organizational Behavior',
 'Professor of Economics and Graduate Coordinator',
 'Professor/Department Chair',
 'Associate Professor & Chair, Department of Landscape Architecture',
 'Director, Honors College',
 'Professor and Program Coordinator of Visual Communication Design',
 'Department Chair',
 'Lecturer Emeritus',
 'Department Chair/Professor, Nutrition',
 'Professor/Executive Director, California State University Agricultural Research Institute',
 'Emerita Faculty',
 'Professor of Entrepreneurship and Creativity',
 'Associate Professor of Entrepreneurship',
 "Lecturer on Ethnic & Women's Studies",
 'Chair / Professor',
 'Adjunct Lecturer',
 'Professor of English',
 'Faculty',
 'Assistant Professor (Tenure-Track), CEMaST Faculty Scholar, Graduate Coordinator for Plant Science',
 'Assoc Prof/Directed Teach Coord',
 'Professor/Educational Multimedia Coordinator',
 'Distinguished Professor, Emeritus',
 'Associate Professor, Nutrition/Director, Didactic Program in Dietetics',
 'Associate Professor and Program Director for Social Work',
 'Associate Professor, Nutrition/Graduate Coordinator',
 'Assistant Professor, Nutrition/Nutrition Coordinator',
 'Professor of Structural Engineering',
 'Emeritus Professor',
 'Lecturer Emeritus CIS/CBA',
 'Professor, Food Science; Associate Dept. Chr.',
 'Associate Professor of Geography',
 'Associate Professor Emeritus',
 'Professor of Construction Engineering and Management & Graduate Coordinator',
 'Professor, Food Science/Executive Director of External Relations',
 'Associate Professor of Strategic Management',
 'Equine Lecturer/Compliance and Safety Specialist',
 'Associate Professor, Advisor',
 'Interim Associate Dean/Professor',
 'Professor of Human Resources',
 'Professor & Department Chair',
 'Professor of Leadership',
 'Professor, Advisor',
 'Associate Professor, Interdisciplinary Arts',
 'Professor of Mathematics',
 'Associate Professor STEM Pedagogy, First Year Coordinator College of Engineering',
 'Adjunct Faculty',
 'Prof Emeritus',
 'Associate Professor of Human Resources',
 'Department Chair/Professor',
 'Professor and Chair',
 'FRL Faculty',
 'Library Faculty',
 'Professor, IBM Chair',
 'Ph.D., Professor',
 'Professor and Department Chair',
 'Assistant Professor, Nutrition',
 'Chair & Professor of Geography',
 'Professor, ASME Fellow, AIAA Assoc Fellow',
 'Professor of Geography',
 'Associate Professor, Composition Coordinator',
 'English Lecturer',
 'Assistant Professor, Advisor',
 'Assistant Professor, Finance',
 'Professor of Management',
 'Professor Emerita Geography',
 'Department Chair and Professor',
 'Professor, Structural and Earthquake Engineering',
 'Lecturer, IBM Department | Program Coordinator, MSBA',
 'Assistant Professor, Kinesiology & Health Promotion, College of Science',
 'Director of Global Leadership Initiative',
 'Instructional Faculty/Lecturer',
 'Chair',
 'Professor of Anthropology',
 'Professor Emeritus, Food Science and Technology',
 'Professor and Director',
 'Professor and Interim Department Chair',
 'Professor and Director of Singelyn Graduate School of Business',
 'Assistant Professor of Organizational Behavior',
 'Electronic Resources Management Librarian',
 'Professor & Associate Chair',
 'Assistant Professor, Food Science',
 'Director, Singelyn Graduate School of Business & Associate Professor of Entrepreneurship and Strategic Management',
 'Director of Weglyn Endowed Chair',
 'Professor of Linguistics and TESOL',
 'Interim Department Chair/Professor/ARI Campus Coordinator',
 'Professor Emerita & Director Emerita Motor Development Clinic',
 'Professor Emeritus and Provost Fellow',
 'Emeritus Lecturer',
 'Lecturer/Director, Dietetic Internship Program/Director, M.S. in Dietetics Program',
 'Associate Professor and Graduate Coordinator',
 'Professor Ram Ronen',
 'Dr. Renford Reese',
 'Department Chair/Associate Professor',
 'Faculty Emerita',
 'Rosie Nawpar',
 'Letcurer',
 'Assistant Professor of Geography',
 'Emerita',
 'Chair & Professor',
 '.',
 'Associate Professor and Chair',
 'Lecturer/Estudiante de Dietética Program Administrator',
 'Professor of Biological Sciences & Director of Discovery Camp Program',
 "Physic's Faculty",
 'Professor & Chair',
 'Professor and Director, Kellogg Honors College',
 'Professor Emeritus of Geography',
 'Professor and Interim Co-Chair',
 'Adjunct/Lecturer',
 'Dr. Timothy Corcoran',
 'Professor of Entrepreneurship',
 'Assistant Professor of Leadership',
 'Assistant Professor of Applied Linguistics and TESOL',
 'Associate Professor & Graduate Coordinator',
 'Lecturer/Director Center for the Advance of Faculty Excellence (CAFE)',
 'Professor, James A. Collins Distinguished Professor',
 'Lecturer/ARI Campus Point Person',
 'Professor/Graduate Coordinator',
 'Professor and Associate Chair',
 'Department Chair, Professor',
 'Assistant Professor of Environmental & Health Justice',
 'Associate Professor, Food Science',
 'Professor of Human Resources & Chair',
 'Professor, Food Engineering',
 'Assistant Professor of Marketing (Tenure Track)',
 'Professor, Exercise Science Program Director, BASES program Director',
 'Professor of Management and Leadership',
 'Chair, Professor, MSIS Director']

In [103]:
titles = (
    pomona_df["title"]
    .astype("string")
    .str.strip()
)

pattern = (
    r"(?i)\b("
    r"Senior Assistant Librarian|"
    r"Assistant Professor|"
    r"Associate Professor|"
    r"Professor|"
    r"Adjunct Professor|"
    r"Full-Time Lecturer|"
    r"Lecturer|"
    r"Librarian"
    r")\b"
)

matched = titles.str.extract(pattern, expand=False)
pomona_df["title_clean"] = matched.str.title().fillna(titles)
# Keep unmatched titles for review instead of dropping them.
pomona_df["title"] = pomona_df["title_clean"].fillna(pomona_df["title"])
pomona_df.drop(columns=["title_clean"], inplace=True)
allowed_titles = [
    "Assistant Professor",
    "Teacher",
    "Associate Professor",
    "Professor",
    "Lecturer",
    "Lecturer AY",
    "Instructional Faculty",
    "Instructor",
    "Chair",
    "Director",
    "Grsf If 12",
    "Adjunct Professor",
    "Associate Librarian",
    "Librarian",
    "Adjunct Assistant Professor",
    "Associate Clinical Professor",
    "Senior Lecturer",
    "Full-Time Lecturer",
    "Full-time Temporary",
]

pomona_df = pomona_df[pomona_df["title"].isin(allowed_titles)].copy()

pomona_output = Path(pomona_data).with_name("pomona_cleaned.parquet")
pomona_df.to_parquet(pomona_output, index=False)
pomona_df.head(5)

,name,school,department,title,major
0,Aaron Cayer,Cal Poly Pomona,Architecture,Associate Professor,<NA>
1,Aaron Fox,Cal Poly Pomona,Department of Plant Science,Associate Professor,<NA>
2,Aaron DeRosa,Cal Poly Pomona,English and Modern Languages,Assistant Professor,<NA>
3,Abdelfattah Amamra,Cal Poly Pomona,Computer Science,Associate Professor,<NA>
5,Abigail Clarke,Cal Poly Pomona,Department of Nutrition and Food Science,Assistant Professor,<NA>

In [108]:
pomona_df.shape

(817, 5)

In [25]:
sanbern_df = pd.read_parquet(sanbern_data)
sanbern_df.head(10)

,name,school,department,title,major
0,AJ Hernandez,CSU San Bernardino,Academic Affairs - Office of the Vice President,Administrative Support Coordinator,<NA>
1,Aaron Bookman,CSU San Bernardino,Facilities Services - Grounds,Light Automotive Equipment Operator,<NA>
2,Aaron Brown,CSU San Bernardino,Ethnic Studies,Assistant Professor,<NA>
3,Abbas Quamar,CSU San Bernardino,Special Education Rehabilitation and Counseling,Professor,<NA>
4,Abdul Motin Howlader,CSU San Bernardino,"Computer Science and Engineering, School of",Lecturer,<NA>
5,Abigail Arguijo,CSU San Bernardino,Student Health Center,Pharmacist,<NA>
6,Abigail Mutya,CSU San Bernardino,Nursing,Lecturer,<NA>
7,Abigail Spivey,CSU San Bernardino,Coyote Bookstore,<NA>,<NA>
8,Acquillahs Muteti,CSU San Bernardino,Teacher Education and Foundation,Lecturer,<NA>
9,Ada Fung,CSU San Bernardino,Special Education Rehabilitation and Counseling,Lecturer,<NA>

In [105]:
sanbern_df['title'].unique().tolist()

['Administrative Support Coordinator',
 'Light Automotive Equipment Operator',
 'Assistant Professor',
 'Professor',
 'Lecturer',
 'Pharmacist',
 <NA>,
 'Admissions Processor',
 'Director, Community Engagement and Philanthropy, Palm Desert Campus',
 'Athletic Trainer',
 'Systems Administrator',
 'Groundsworker',
 'Human Resources Professional',
 'Admissions Counselor / Recruiter',
 'Teacher',
 'Philanthropic Grants Research and Development Professional',
 "Interim Associate Vice President, Student Equity and Director of Veteran's Center",
 'Administrative Analyst, Strategic Enrollment Management & Marketing',
 'Master Teacher',
 'Plumber',
 'Senior Media Relations Specialist',
 'Keyboard Collaborative Artist',
 'Associate Director for Housing Facilities',
 'Program Administrative Coordinator',
 'Custodian',
 'Director',
 'Exhibition Preparator',
 'Community Manager Lead Content Developer',
 'Senior Budget Analyst',
 'Business Systems Analyst',
 'Administrative Analyst/Specialist',
 'Library Services Specialist',
 'Parking & Transportation Support Coordinator',
 'Painter',
 'Associate Professor',
 'Health Educator-Wellness Coordinator',
 'Instructional Support Technician',
 'Program Manager',
 'Event Scheduling Coordinator',
 'Admissions Counselor',
 'Technology Support Specialist',
 'Operations Coordinator',
 'Senior Executive Director, Employee & Labor Relations',
 'University Registrar and Director',
 'Student Services Professional',
 'HR Representative',
 'Fire and Life Safety Specialist',
 'Multimedia Language Center Coordinator',
 'Lead Custodian',
 'Director of Donor Relations',
 'Director, Academic Centers for Excellence',
 'Department Chair',
 'Financial Aid Processor',
 'Associate Dean, Social and Behavioral Sciences',
 'CCAMPIS Director',
 'Market Leader',
 'Director, Procure to Pay, Travel and Disbursement',
 'Student Engagement Coordinator',
 'Per Diem Non-Exempt Health Care (Pharmacist)',
 'Medical Assistant',
 'Lead Talent Acquisition Partner',
 'Credential Analyst',
 'Head, Electronic Resources',
 'Procurement Professional',
 'Education Abroad Specialist',
 'Assessment Analyst',
 'Full Time Lecturer',
 'Director, Professional Development and Employee Enrichment',
 'Athletic Equipment Attendant',
 'JHBC College Office Coordinator',
 'Caseworker',
 'Assistant to the Associate Vice President',
 'Accounting Technician',
 'Maintenance Specialist',
 'Software Developer',
 'Academic Advisor',
 'Insitutional Research Analyst',
 'Director of Studio Incubator',
 'Laborer',
 'Senior Graphic Designer',
 'Instructional Support Assistant',
 'Faculty Senate Coordinator',
 'Director, Marketing and Brand Management',
 'New Student and Family Program Coordinator',
 'Community Service Specialist',
 'Lead Procurement and Contract Specialist',
 'Student Placement and Fieldwork Support Coordinator',
 'Security',
 'Director, Basic Needs & Student Support',
 'Executive Director, Budget and Resource Management',
 'Associate Dean',
 'Accessibility Coordinator',
 'Electrician Apprentice',
 'Associate Director of Operations',
 'Building Service Engineer',
 'Electrician',
 'Advancement Reporting and Data Analyst/Specialist',
 'Assistant Athletic Trainer',
 'Survivor Advocate',
 'Facilities Maintenance Mechanic',
 'Parking Officer',
 'Program Admissions Advisor',
 'Coaching Assistant',
 'Police Dispatcher',
 'Marketing, Membership and Engagement Coordinator',
 'Athletics Academic Advisor',
 'Graphic Designer',
 'Philanthropic Giving Analyst',
 'Lead Coordinator, Coyotes Achieve Program',
 'Associate Director, Special Events and Guest Services',
 'Executive Director, Student Engagement and Completion',
 'Confidential Administrative Support',
 'Student Mentor Program Coordinator',
 'Interim Associate Dean',
 'Executive Director of Health, Counseling and Wellness',
 'Graduate Admissions Professional',
 'Technology Support Speclst IV',
 'SSP III',
 'Annuitant Facilities Project Supervisor',
 'User Experience Analyst',
 'Librarian',
 'AVP,Fac Dev & Chief Acad Tech',
 'Coaching Specialist',
 'Director, Black Student Success',
 'Director of Support Services',
 'Honors Student Engagement Coordinator',
 'Director, Administrative Computing and User Experience',
 'Executive Assistant, Office of the Vice President for Human Resources',
 'Fiscal Support Coordinator',
 'Director, Information Security and Compliance',
 'Director,Orient&TransitionProg',
 'Supervising Building Service Engineer',
 'Equity & Compliance Coordinator',
 'Accommodations Coordinator',
 'Assistant to the University Registrar and Director',
 'Web Developer',
 'Job Developer',
 'Academic Coordinator',
 'Health Professions Advising Coordinator',
 'Deputy Chief Information Officer',
 'Program Coordinator',
 'Performing Arts Technician',
 'Payroll Technician',
 'Assistant Manager, Custodial',
 'Transfer and Articulation Coordinator',
 'Budget and Resource Planning Analyst',
 'Program Support Coordinator',
 'Administrative Analyst Specialist',
 'Basic Needs & Student Support Coordinator',
 'Manager, Capital Outlay Administration',
 'Assistant Director, CHRS and Finance System',
 'Administrative Assistant',
 'Associate Dean, Natural Sciences',
 'Disability Specialist',
 'Director, Philanthropy',
 'Assistant to the AVP of ASUA',
 'Success Counselor',
 'Office Manager',
 'Dean of Graduate Studies',
 'Certified Plumber Apprentice',
 'Student Services Professional, Academic Related',
 'Accounts Payable Technician',
 'Costume Technician',
 'Financial Aid Advisor',
 'Registered Nurse',
 'Senior Grants and Contracts Officer',
 'Head, Acquisition and Gifts',
 'Enrollment Services Specialist',
 'Police Officer',
 'Center Manager',
 'Associate Director, Culture and Climate',
 'Enrollment Services Coordinator',
 'Program Coordinator, TCAP',
 'Dean, Watson College of Educ.',
 'Director of Strategic Technology Initiatives',
 'Accountant',
 'Transfer Programs and Orientation Coordinator',
 'Graduate Studies WebAdMIT and Budget Specialist',
 'Administrative Analyst',
 'Senior Associate Athletics Director',
 'Dean, College of SBS',
 'Project Manager, Facilities Planning, Design and Construction',
 'Budget Analyst',
 'Director, School of Criminology and Criminal Justice',
 'Head Coach',
 'Director, Student Financial Services',
 'Executive Assistant to the Associate Vice President',
 'Water Resources Institute Specialist',
 'Administrative Support Assistant',
 'School Director, School of Cyber and Decision Sciences',
 'Associate Director',
 'Digital Media Production Specialist',
 'Corporate Card Specialist',
 'Director of Alumni Relations',
 'Athletics Communication and Marketing Specialist',
 'Lead Community Service Specialist',
 'Financial Aid Technician',
 'Liberal Studies Support Coordinator',
 'Graduate Admissions Support Coordinator',
 'Financial Aid Data, Technology and Web Specialist',
 'Finance & Administrative Coordinator',
 'Physician',
 'Creative Specialist',
 'Academic Budget and Planning Specialist',
 'Crime Analyst',
 'Network Analyst',
 'Disabilites Specialist',
 'Vice President, Strategic Enrollment Management and Marketing',
 'Campus Inspector',
 'Event Coordinator',
 'Instr Fac AY',
 'Tutoring Program Coordinator',
 'Library Service Specialist',
 'Assistant to the Dean',
 'EOP Counselor',
 'Sponsored Programs Specialist',
 'MBA Program Coordinator',
 'Executive Assistant',
 'Office Coordinator',
 'Scheduling & Curriculum Analyst',
 'Housing Navigator',
 'Licensed Vocational Nurse',
 'Property Clerk',
 'Interim Lieutenant',
 'Executive Director, Financial Aid & Scholarship',
 'College Specialist',
 'Payroll Manager',
 'Employee and Labor Relations Business Partner',
 'Instructional Designer',
 'Alumni Operations Coordinator',
 'College Grant Coordinator',
 'Library Access Services Specialist',
 'Interim Manager, Parking Services',
 'Pell Grant Advisor',
 'Dean, Palm Desert Campus',
 'Director, Advising & Academic Services',
 'Operating Systems Analyst',
 'Recruitment Enrollment & Retention Coordinator',
 'Police Dispatcher Lead',
 'Director of Program Operations',
 'Immigration Specialist',
 'Clinic Coordinator/Lead Registered Nurse',
 'Prevention, Education and Compliance Manager',
 'Executive Assistant to Associate Vice President',
 'Department Administrative Support Coordinator',
 'Associate Director, Digital Brand Strategy',
 'Health Educator',
 'Academic Success Coordinator',
 'Research Analyst',
 'Manager of Facilities Planning & Space Utilization',
 'Director of Administration',
 'Associate Librarian',
 'Library Services Fiscal & Operations Analyst',
 'Advisor/Peer Advisor',
 'Executive Assistant to the Chief of Police',
 'Full time Lecturer',
 'Degree Planner Analyst',
 'Reprographics Specialist',
 'Facilities Project Supervisor',
 'Office Support Coordinator',
 'Retention Coordinator',
 'Prospect Research Specialist',
 'Faculty Program Administrator',
 'Pest Control And Spray Specialist',
 'Library Operations Coordinator',
 'Early Assessment Program Coordinator',
 'Executive Assistant to the Dean',
 'Financial Aid Wellness Coordinator',
 'Media Production Specialist',
 'Senior Manager, Budget and Resource Planning',
 'Follett Access Program Lead',
 'Case Management Specialist',
 'Lead Software Engineer',
 'Equipment Maintenance Assistant',
 'Warehouse Worker',
 'Transfer and Graduation Counselor',
 'Supervising Plumber',
 'Chief Information Officer',
 'Senior Technology Strategist',
 'Assistant Director, Philanthropy',
 'Director, Special Events and Guest Services',
 'Faculty Support Coordinator',
 'Director, Campus Operations',
 'Director of Parking and Transportation Services',
 'Lead, Accounts Payable & Procure to Pay',
 'Summer Director',
 'CNS Associate Dean and Director of Strategic Partnerships',
 'Facilities Central Specialist',
 'Museum Lead, Exhibition Designer',
 'Manager, Operations',
 'Manager, Custodial Services',
 'Manager, Human Resources',
 'Phlebotomist/Clinical Laboratory Assistant',
 'Temp Admin Support',
 'Student Services Coordinator',
 'Associate Director, International Student and Scholar Services',
 'Admin Support Assistant 12 Mo',
 'Financial Operations Analyst',
 'Enrollment Services Advisor',
 'Director for Student Engagement',
 'Mail Clerk',
 'Outreach Counselor',
 'Accounting Services Lead',
 'Gift Processing Coordinator',
 'Veterans Success Advisor/School Certifying Official',
 'Director, Undocumented Student Success Center',
 'Business Manager - PDC MSW Program',
 'Director of Research and Development',
 'Special Collections & University Archives Specialist',
 'Lead Information Security Analyst',
 'Equipment Specialist',
 'Director, Multimedia and Immerse Technologies',
 'Assistant to the Provost and Vice President',
 'Marketing Manager',
 'Events Specialist',
 'Fitness Coordinator',
 'Principal Investigator',
 'Executive Director',
 'Housing Coordinator',
 'Executive Director and Chief Procurement Officer',
 'Chief of Staff,AA/Director,ABP',
 'Alumni Relations Professional',
 'Scholarship Program Lead',
 'PI - RDM Infrastructure',
 'Director, CAPS',
 'Chief Administrative Officer',
 'PAWS Lead Program Assistant',
 'STEM Counsleor',
 'Service and Project Support Coordinator',
 'Transfer & Graduation Counselor - CEGE',
 'Administrative Analyst, Academic Research',
 'Student Success Center Coordinator',
 'Payroll Lead',
 'Donor Relations Coordinator',
 'Music Performing Arts Technician',
 'Institutional Equity & Compliance Investigator',
 'Graduate Student Services Professional',
 'Lead Scholarship and Foundation Operations Analyst',
 'Information Security Compliance Specialist',
 'Marketing Communication Professional',
 'uAchieve and OnBase Data Processor',
 'Event Specialist',
 'Facilities Administrative Services Lead',
 'Digital Transformation Lead',
 'Academic Scheduler & Faculty Support Coordinator',
 'Web Accessibility Coordinator',
 'Lead Technology Support Specialist',
 'Associate Director, Employee & Labor Relations',
 'Sergeant',
 'Facilities Control Specialist',
 'Payroll Coordinator',
 'Practicum Business Manager',
 'Administrative Assistant II',
 "Workers' Compensation Program Manager",
 'Area Coordinator',
 'Financial Systems Analyst Specialist',
 'Assistant Stockroom Coordinator',
 'Graduate Admissions Specialist',
 'Director, Housing and Residential Education',
 'Auto/Equipment Mechanic',
 'Academic Budget and Planning Lead Analyst',
 'Special Case Advisor',
 'Automotive Equipment Mechanic',
 'Lead HR Professional, Student Employment',
 'Director of Hospitality Management',
 'Senior Coordinator, Student Diversity and Belonging',
 'Membership Coordinator',
 'International Admissions Processor',
 'Manager, Classification and Compensation',
 'Director, Facilities Management',
 'Maintenance Custodian',
 'Lead Groundsworker',
 'Supervisor',
 'Director, Office of Sponsored Programs Administration',
 'Public Service and Stack Maintenance Lead',
 'Director, Talent Acquisition',
 'PDC Administrative Analyst/Specialist',
 'Head, Inter Library Loans',
 'Department Chair - AY',
 'Associate Director, Compliance and Strategic Initiatives',
 'Executive Director, Audit & Advisory Services',
 'Payroll Assistant',
 'Wellness Coach',
 'Physician Assistant',
 'Registration and Information Specialist',
 'CCAMPIS Coordinator',
 'Program Manager/Assistant Director CAE',
 'Associate Vice President and Chief of Staff',
 'Administrative and Financial Analyst',
 'Writing Center Coordinator',
 'Graduate Student Success Center/Program Board Coordinator',
 'Director, Coyote Central',
 'Marketing Communications Professional',
 'Director/Instructor',
 'VP, Academic Programs',
 'Analyst/Programmer',
 'Lead Locksmith',
 'SSP II',
 'Associate Controller of Accounting Services',
 'Leave of Absence & ADA Specialist',
 'Operations & Logistics Analyst',
 'Athletics Administrative Analyst',
 'Graduate Systems Analyst',
 'User Experience Analyst II',
 'Staffing and Budget Analyst',
 'Lead, Transfer Graduation Unit',
 'Director SAIL',
 'Associate Director, Deputy Title IX Coordinator for Institutional Equity and Compliance',
 'Event Budget Specialist',
 'International Admissions Evaluator',
 'Orientation Program Coordinator',
 'Executive Assistant to the Vice President',
 'Administrator II',
 'Graphic Specialist',
 'Campus Store Leader for PDC',
 'Project Analyst',
 'Career Counselor/Advisor',
 'Assistant to the Executive Director of Financial Aid & Scholarships',
 'TCAP Teacher Leader 1',
 'AVP, ASUA',
 'Financial Aid Technician/Federal Work Study Coordinator',
 'Residential Education Leadership Coordinator',
 'Interim Director',
 'Database Administrator',
 'Operations Analyst',
 'Associate Dean of Students and Director of Student Conduct and Ethical Development',
 'Research Technician',
 'Lead Program Admissions Technician',
 'Director, Student Diversity and Belonging',
 'Professional Advisor',
 'Athletics Game Operations Specialist',
 'Executive Director of Risk Management',
 'Veterans Success Center Finance & Administrative Coordinator',
 'Multimedia Communication Specialist',
 'Travel Department Lead',
 'Operations Support Coordinator',
 'Special Collections Specialist',
 'Student Assistant Teacher',
 'Director, Government and Community Relations',
 'GAAP Accountant',
 'University Controller',
 'Alumni Mentor Specialist',
 'Talent Acquisition Partner',
 'Academic Scheduling Analyst',
 'Training and Program Manager',
 'Accommodation Coordinator',
 'Administrative Support Coordinator/Nutritionist',
 'Student Success Studio Coordinator',
 'Counselor - SAIL',
 'JHBC Communication Specialist',
 'Event Services Manager',
 'Irrigation Specialist',
 'Campus Store Manager',
 'Associate Vice President for Government & Community Relations',
 'Risk and Compliance Specialist',
 'Associate, Academic and Institutional Studies',
 'Program Administrator',
 'Senior Coordinator, Adventure Program',
 'Storekeeper',
 'Chief of Staff and Director of Operations & Fiscal Management for Student Affairs',
 'Facilities and Services Coordinator',
 'Interim Vice President, Student Affairs and Dean of Students',
 'Tech Admin Support',
 'Senior Instructional Designer',
 'Orientation Senior Program Coordinator',
 'Graduate Student Engagement Specialist',
 'Capital Projects and Contract Specialist',
 'Director, Services to Students with Disabilities',
 'Director, Prospect Management and Research',
 'Basic Needs and Administrative Coordinator',
 'Peer Health Education Coordinator',
 'Director, Outreach and Student Recruitment',
 'Interim Associate Registrar, Records and Degree Audits',
 'Academic Systems Administrator',
 'Senior Alumni Engagement Specialist',
 'Director of Digital Transformation',
 'Director of Environmental Health and Safety',
 'Institutional Review Board Analyst',
 'Project Rebound Program Coordinator',
 'International Student Advisor',
 'Printing Services Lead',
 'School Director',
 'Program Director',
 'Assistant to the Dean, Palm Desert Campus',
 'QTRC Coordinator',
 'Assistant Manager, Business Operations',
 'Philanthropic Support Associate, Palm Desert Campus',
 'Senior Director of Philanthropy, Foundation and Corporate Relations',
 'Senior Communication Specialist',
 'Energy and Sustainability Manager',
 'Veterans Success Advisor',
 'AVP for Operations',
 'Student Affairs Marketing and Communication Specialist',
 'Health Information Technician',
 'Budget Analyst III',
 'Graphic & Multimedia Designer',
 'Student Services Assistant',
 'Senior Director, Research and Sponsored Programs',
 'Information Security Analyst',
 'Lead International Admissions Evaluator',
 'Basic Needs Senior Program Coordinator',
 'Co PI',
 'Video Production Specialist',
 'Interim Associate Provost, Faculty Affairs & Development',
 'EOP Admissions Counselor',
 'Career Readiness Program Coordinator, PDC',
 "Women's Resource Coordinator",
 'Career Services Advisor',
 'Organizational Change Facilitator',
 'Director, Tribal Relations',
 'Facilities Operations Lead',
 'Associate Director Financial Aid & Operations',
 'Head Athletic Trainer',
 'Supervising Painter',
 'System Administrator',
 'HR Professional',
 'Degree Audit Coordinator',
 'Provost and Vice President for Academic Affairs',
 'Accounts Payable and Travel Analyst',
 'Receiving Assistant',
 'Manager, Landscape & Site Development',
 'Compliance and Employee Engagement Specialist',
 'Interim Vice President, University Advancement & Executive Director, CSUSB Philanthropic Foundation',
 'Dean, Pfau Library',
 'Locksmith',
 'Project Coordinator',
 'DHRE Administrative Support Coordinator',
 'Information Technology and Esports Manager',
 'Compliance Specialist',
 'Lead Physician',
 'Deputy Chief of Staff',
 'Classification and Compensation Analyst',
 'Professor Emeritus',
 'Senior Associate Vice President, Marketing and Communications',
 'Vice President, Human Resources and Senior Diversity Officer',
 'Police Captain',
 'Faculty Affairs and Development Lead Analyst',
 'Academic Programs Analyst',
 'Physical and Visual Disabilities Specialist (PDC)',
 'Dean, College of Arts & Letter',
 'UEC HR Benefits Coordinator',
 'Communications Professional',
 'Co-PI',
 'Executive Director of Facilities Planning, Design & Construction',
 'Lecturer 12 Month',
 'Child Welfare Specialist',
 'Project Manager',
 'Chatbot Communication Consultant',
 'Chief Financial Officer and Vice President, Finance, Technology and Operations',
 'Director, Payroll and Benefits Services',
 'Director, Mentoring & College Advising',
 'Program Specialist',
 'Director, Operations and Fiscal Management',
 'Area Coordinator for Residential Education',
 'Dean, College of Natural Sci.',
 'Environmental Health Safety Professional II',
 'Police Detective',
 'Publicity Specialist',
 'Interim Director of Operations, Recreation and Wellness',
 'Assistant Director, Student Conduct & Ethical Development',
 'Supervising Locksmith',
 'Associate Vice President, Finance & Administrative Services',
 'Security Guard',
 'Director of Athletics',
 'Administrative Analyst II',

In [106]:
titles = (
    sanbern_df["title"]
    .astype("string")
    .str.strip()
)

pattern = (
    r"(?i)\b("
    r"Senior Assistant Librarian|"
    r"Assistant Professor|"
    r"Associate Professor|"
    r"Professor|"
    r"Adjunct Professor|"
    r"Full-Time Lecturer|"
    r"Lecturer|"
    r"Librarian"
    r")\b"
)

matched = titles.str.extract(pattern, expand=False)
sanbern_df["title_clean"] = matched.str.title().fillna(titles)
# Keep unmatched titles for review instead of dropping them.
sanbern_df["title"] = sanbern_df["title_clean"].fillna(sanbern_df["title"])
sanbern_df.drop(columns=["title_clean"], inplace=True)
allowed_titles = [
    "Assistant Professor",
    "Teacher",
    "Associate Professor",
    "Professor",
    "Lecturer",
    "Lecturer AY",
    "Instructional Faculty",
    "Instructor",
    "Chair",
    "Director",
    "Grsf If 12",
    "Adjunct Professor",
    "Associate Librarian",
    "Librarian",
    "Adjunct Assistant Professor",
    "Associate Clinical Professor",
    "Senior Lecturer",
    "Full-Time Lecturer",
    "Full-time Temporary",
]

sanbern_df = sanbern_df[sanbern_df["title"].isin(allowed_titles)].copy()

sanbern_output = Path(sanbern_data).with_name("sanbern_cleaned.parquet")
sanbern_df.to_parquet(sanbern_output, index=False)
sanbern_df.head(5)

,name,school,department,title,major
2,Aaron Brown,CSU San Bernardino,Ethnic Studies,Assistant Professor,<NA>
3,Abbas Quamar,CSU San Bernardino,Special Education Rehabilitation and Counseling,Professor,<NA>
4,Abdul Motin Howlader,CSU San Bernardino,"Computer Science and Engineering, School of",Lecturer,<NA>
6,Abigail Mutya,CSU San Bernardino,Nursing,Lecturer,<NA>
8,Acquillahs Muteti,CSU San Bernardino,Teacher Education and Foundation,Lecturer,<NA>

In [107]:
sanbern_df.shape

(1165, 5)

In [115]:
dh_df = pd.read_parquet(dh_data)
dh_df.head(10)

,name,title,department,school,year
0,Yann Abdourazakou,Professor of Management and Marketing,Management and Marketing,"California State University, Dominguez Hills",2015
1,Jennifer Adeva,"Head Coach, Volleyball",,"California State University, Dominguez Hills",2011
2,Benyamin Ahmadnia,Assistant Professor of Computer Science,Computer Science,"California State University, Dominguez Hills",2024
3,Adekunle Aina,Assistant Professor of Physics,Physics,"California State University, Dominguez Hills",2024
4,Adriana Aldana,Associate Professor of Social Work,Social Work,"California State University, Dominguez Hills",2015
5,Amy Allen,Associate Professor of Dance,Dance,"California State University, Dominguez Hills",2018
6,Cathryn Andrade,Assistant Professor of Nursing,Nursing,"California State University, Dominguez Hills",2018
7,Terri Ares,Associate Professor of School of Nursing,School of Nursing,"California State University, Dominguez Hills",2015
8,Nallely Arteaga,Assistant Professor of Teacher Education,Teacher Education,"California State University, Dominguez Hills",2020
9,Hugo Asencio,Professor of Public Administration,Public Administration,"California State University, Dominguez Hills",2013

In [116]:
# Replace df with your dataframe name.
titles = (
    dh_df["title"]
    .astype("string")
    .str.strip()
    .str.replace(r"\bAssoiciate\b", "Associate", regex=True, case=False)
    .str.replace(r"\bProfesssor\b", "Professor", regex=True, case=False)
)

# Put more specific titles before their shorter versions.
pattern = (
    r"(?i)\b("
    r"Senior Assistant Librarian|"
    r"Assistant Professor|"
    r"Associate Professor|"
    r"Professor|"
    r"Full-Time Lecturer|"
    r"Lecturer|"
    r"Librarian"
    r")\b"
)

matched = titles.str.extract(pattern, expand=False)
dh_df["title_clean"] = matched.str.title().fillna(titles)
# Keep unmatched titles for review instead of dropping them.
dh_df["title"] = dh_df["title_clean"].fillna(dh_df["title"])
dh_df["title"] = dh_df["title"].replace(
    "AssociateProfessor of Physical Therapy",
    "Associate Professor"
)
dh_df.drop(columns=["title_clean"], inplace=True)
dh_df.head(10)

,name,title,department,school,year
0,Yann Abdourazakou,Professor,Management and Marketing,"California State University, Dominguez Hills",2015
1,Jennifer Adeva,"Head Coach, Volleyball",,"California State University, Dominguez Hills",2011
2,Benyamin Ahmadnia,Assistant Professor,Computer Science,"California State University, Dominguez Hills",2024
3,Adekunle Aina,Assistant Professor,Physics,"California State University, Dominguez Hills",2024
4,Adriana Aldana,Associate Professor,Social Work,"California State University, Dominguez Hills",2015
5,Amy Allen,Associate Professor,Dance,"California State University, Dominguez Hills",2018
6,Cathryn Andrade,Assistant Professor,Nursing,"California State University, Dominguez Hills",2018
7,Terri Ares,Associate Professor,School of Nursing,"California State University, Dominguez Hills",2015
8,Nallely Arteaga,Assistant Professor,Teacher Education,"California State University, Dominguez Hills",2020
9,Hugo Asencio,Professor,Public Administration,"California State University, Dominguez Hills",2013

In [118]:
dh_df.shape
dh_output = Path(sanbern_data).with_name("csudh_cleaned.parquet")
dh_df.to_parquet(dh_output, index=False)
dh_df.head(5)

,name,title,department,school,year
0,Yann Abdourazakou,Professor,Management and Marketing,"California State University, Dominguez Hills",2015
1,Jennifer Adeva,"Head Coach, Volleyball",,"California State University, Dominguez Hills",2011
2,Benyamin Ahmadnia,Assistant Professor,Computer Science,"California State University, Dominguez Hills",2024
3,Adekunle Aina,Assistant Professor,Physics,"California State University, Dominguez Hills",2024
4,Adriana Aldana,Associate Professor,Social Work,"California State University, Dominguez Hills",2015